smiley_groups = [
    [':dunno:'],
    [':)', ':D', ':-D', ':lol:', ':ololo:', ':evil:', '+_+', ':cool:', ':thumbup:', ':yahoo:', ':tea2:', ':star:'],
    [':oh:', ':shy:', ':shy2:', ':hurray:', ':roll:', ':!:', ':watching:', ':love:', ':love2:', ':bunch:',
     ':perveted:'],
    [':very sad:', ':depressed:', ':depressed2:', ':hopeless:', ':very sad2:', ':cry:', ':cry6:',
     ':Cry2:', ':Cry3:', ':Cry4:'],
    [':shock:', ':shock2:', ':scream:', ':dont want:', ':noooo:', ':scared:', ':shocked2:', ':shocked3:',
     ':shocked4:',
     ':tea shock:', ':frozen3:'],
    [':angry4:', ':revenge:', ':evil2:', ':twisted:', ':angry:', ':angry3:', ':angry5:', ':angry6:', ':cold:',
     ':strange4:', ':ball:', ':evil3:'],
    [':8):', ':oh2:', ':ooph:', ':wink:', ':dunno:', ':dont listen:', ':hypno:', ':advise:', ':bored:',
     ':disappointment:', ':hunf:'],
    [':hot:', ':hot2:', ':hot3:', ':stress:', ':strange3:', ':strange2:', ':strange1:', ':Bath2:', ':strange:',
     ':hope:', ':hope3:', ':diplom:'],
    [':hi:', ':bye:', ':sleep:', ':bow:', ':Warning:', ':Ban:', ':Im dead:', ':sick:', ':s1:', ':s3:', ':s2:',
     ':happy_cry:'],
    [':ill:',
     ':sad2:',
     ':bullied:', ':bdl2:',
     ':Happy Birthday:', ':flute:',
     ':cry5:',
     ':gaze:', ':hope2:',
     ':sleepy:',
     ':study:', ':study2:', ':study3:', ':gamer:',
     ':animal:',
     ':caterpillar:',
     ':cold2:', ':shocked:', ':frozen:', ':frozen2:', ':kia:', ':interested:',
     ':happy:',
     ':happy3:',
     ':water:', ':dance:', ':liar:', ':prcl:',
     ':play:',
     ':s4:', ':s:',
     ':bath:',
     ':kiss:', ':whip:', ':relax:', ':smoker:', ':smoker2:', ':bdl:', ':cool2:',
     ':V:', ':V2:', ':V3:',
     ':sarcasm:', ':angry2:', ':kya:']
]
